# Generated by Django 4.1.4 on 2023-06-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_key', models.FileField(upload_to='media/')),
                ('file_url', models.CharField(max_length=300)),
            ],
        ),
    ]
