# Generated by Django 4.1.4 on 2023-06-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file_key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
