# Generated by Django 4.1.4 on 2023-06-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_documents_file_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
